version: "3"

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    command: mongod --replSet myReplSet
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
